spring:
  application:
    name: vgr-assignment
springdoc:
  api-docs:
    path: /docs
  swagger-ui:
    path: /box

article-types:
  types:
    1:
      width: 1
      length: 1
    2:
      width: 1
      length: 2
    3:
      width: 1
      length: 4
    4:
      width: 1
      length: 6
    5:
      width: 1
      length: 8
    6:
      width: 1
      length: 9
    7:
      width: 1
      length: 12
    8:
      width: 1
      length: 5
    9:
      width: 1
      length: 9

boxes:
  types:
    1:
      width: 4
      length: 5
    2:
      width: 8
      length: 12
    3:
      width: 12
      length: 20
